package org.coderfun.fieldmeta.service;

import org.coderfun.fieldmeta.dao.TemplateFileDAO;
import org.coderfun.fieldmeta.entity.TemplateFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import klg.j2ee.common.dataaccess.BaseServiceImpl;



/**
 *
 * 
 * Generated by fieldmeta at 2019-08-10T13:41:41+08:00
 *
 */
 
@Service
public class TemplateFileServiceImpl  extends BaseServiceImpl<TemplateFile, Long> implements TemplateFileService{
	@Autowired
	TemplateFileDAO templateFileDAO;
}
