package org.coderfun.fieldmeta.service;

import java.io.IOException;

import org.coderfun.fieldmeta.entity.TemplateFile;

import klg.j2ee.common.dataaccess.BaseService;



/**
 *
 * 
 * Generated by fieldmeta at 2019-08-10T13:41:41+08:00
 *
 */
 
public interface TemplateFileService extends BaseService<TemplateFile, Long>{
	static final String TEMPLATE_DIR_KEY = "/template/";
	static final String UPLOAD_TEMP_DIR_KEY = "/upload/temp/";
	
	public String getRealPath(TemplateFile templateFile);
	public String getUploadTempDir();
	
	public byte[] getAllFilesByZip() throws IOException;
}
