package org.coderfun.fieldmeta.service;

import org.coderfun.fieldmeta.entity.TemplateFile;

import klg.j2ee.common.dataaccess.BaseService;



/**
 *
 * 
 * Generated by fieldmeta at 2019-08-10T13:41:41+08:00
 *
 */
 
public interface TemplateFileService extends BaseService<TemplateFile, Long>{

}
